# 1 워크플로의 이름 지정
name: CI/CD

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ main ]
#on:
#  pull_request:
#    branches: [ "main" ]
#
#permissions:
#  contents: read


jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
#      # json 임시 파일 생성 - json minify
#      - name: Set up Google Cloud Credentials
#        run: |
#          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > google-credentials.json
#          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/google-credentials.json" >> $GITHUB_ENV
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

      # Docker 이미지 빌드 및 Google Container Registry(GCR)에 푸시
      # 아피택트 레지스트리에서 직접 계정을 추가
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia-northeast3-docker.pkg.dev/co-re-413916/co-re-docker/my-app:latest
          file: Dockerfile
          context: . # 현재 GitHub Actions의 작업 디렉토리를 컨텍스트로 사용
          build-args: |
            JAR_FILE=build/libs/*.jar

      # Google Cloud Run에 배포
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: my-app
          image: asia-northeast3-docker.pkg.dev/co-re-413916/co-re-docker/my-app:latest
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}